# Generated by Django 5.1.5 on 2025-01-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique_for_date='publish_time', verbose_name='slug'),
        ),
    ]
